import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { useCallProcedure, Page } from '@kottster/react';
import {
  AreaChart, Area,
  XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Legend,
} from 'recharts';
import {
  Play,
  Zap,
  CheckCircle,
  Gift,
  CreditCard,
  Bot,
  FileText,
} from 'lucide-react';
import { useThemeListener } from '../../utils/theme';
import { AnalyticsHeader } from '../../components/analytics/AnalyticsHeader';
import { AnalyticsStatCard } from '../../components/analytics/AnalyticsStatCard';
import { AnalyticsChartContainer } from '../../components/analytics/AnalyticsChartContainer';
import { AnalyticsTooltip } from '../../components/analytics/AnalyticsTooltip';
import { AnalyticsError } from '../../components/analytics/AnalyticsError';
import {
  DateFilterOptions,
  SeriesConfig,
  SessionDataRow,
} from '../../types';

const DATE_FILTERS: DateFilterOptions[] = [
  { label: 'Today', value: 'today', days: 0 },
  { label: 'Last 7 Days', value: '7', days: 7 },
  { label: 'Last 30 Days', value: '30', days: 30 },
  { label: 'Last 90 Days', value: '90', days: 90 },
  { label: 'Last 6 Months', value: '180', days: 180 },
  { label: 'Last Year', value: '365', days: 365 },
  { label: 'Custom Range', value: 'custom', days: 0 },
];

const SERIES: SeriesConfig[] = [
  { key: 'total_sessions', label: 'Total Sessions', color: '#ca8a04' },
  { key: 'active_sessions', label: 'Active Sessions', color: '#10b981' },
  { key: 'completed_sessions', label: 'Completed Sessions', color: '#8b5cf6' },
  { key: 'free_sessions', label: 'Free Sessions', color: '#06b6d4' },
  { key: 'paid_sessions', label: 'Paid Sessions', color: '#f59e0b' },
  { key: 'auto_generated_sessions', label: 'Auto Generated', color: '#ec4899' },
  { key: 'sessions_with_transcription', label: 'With Transcription', color: '#6366f1' },
];

const validateDateRange = (startDate: string, endDate: string): boolean => {
  if (!startDate || !endDate) return false;
  const start = new Date(startDate);
  const end = new Date(endDate);
  if (isNaN(start.getTime()) || isNaN(end.getTime())) return false;
  return start <= end;
};

const STAT_CARDS = [
  { key: 'total',           label: 'Total Sessions',    icon: Play,        accent: 'yellow' },
  { key: 'active',          label: 'Active Sessions',   icon: Zap,         accent: 'emerald' },
  { key: 'completed',       label: 'Completed',         icon: CheckCircle, accent: 'violet' },
  { key: 'free',            label: 'Free Sessions',     icon: Gift,        accent: 'cyan' },
  { key: 'paid',            label: 'Paid Sessions',     icon: CreditCard,  accent: 'amber' },
  { key: 'autoGenerated',   label: 'Auto Generated',    icon: Bot,         accent: 'pink' },
  { key: 'withTranscription', label: 'With Transcription', icon: FileText, accent: 'indigo' },
] as const;

export default function SessionAnalyticsPage(): React.ReactElement {
  const [rows, setRows] = useState<SessionDataRow[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [refreshing, setRefreshing] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [isDark, setIsDark] = useState<boolean>(false);

  const [dateFilter, setDateFilter] = useState<string>('90');
  const [customStartDate, setCustomStartDate] = useState<string>('');
  const [customEndDate, setCustomEndDate] = useState<string>('');
  const [showCustomDateRange, setShowCustomDateRange] = useState<boolean>(false);

  const [retryCount, setRetryCount] = useState<number>(0);
  const callProcedure = useCallProcedure();
  const abortControllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    const cleanup = useThemeListener((dark: boolean) => setIsDark(dark));
    return cleanup;
  }, []);

  const formatDateString = useCallback((dateStr: string): string => {
    if (!dateStr) return '';
    try {
      const date = new Date(dateStr);
      if (isNaN(date.getTime())) return dateStr;
      return date.toLocaleDateString('en-US', { day: 'numeric', month: 'short' });
    } catch {
      return dateStr;
    }
  }, []);

  const fetchData = useCallback(async (isManualRefresh = false): Promise<void> => {
    if (!callProcedure) return;
    if (abortControllerRef.current) abortControllerRef.current.abort();
    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    try {
      if (isManualRefresh) setRefreshing(true);
      else setLoading(true);
      setError(null);

      let startDate: string | undefined;
      let endDate: string | undefined;

      const now = new Date();
      if (dateFilter === 'today') {
        const todayStr = now.toISOString().split('T')[0];
        startDate = todayStr;
        endDate = todayStr;
      } else if (dateFilter === 'custom') {
        if (customStartDate && customEndDate) {
          startDate = customStartDate;
          endDate = customEndDate;
        }
      } else if (dateFilter !== 'all') {
        const days = parseInt(dateFilter, 10) || 90;
        const start = new Date(now.getTime() - (days * 24 * 60 * 60 * 1000));
        startDate = start.toISOString().split('T')[0];
        endDate = now.toISOString().split('T')[0];
      }

      const data = await (callProcedure as any)('getSessionAnalytics', { startDate, endDate }) as SessionDataRow[];

      if (!abortController.signal.aborted && Array.isArray(data)) {
        setRows(data);
        setRetryCount(0);
      }
    } catch (err) {
      if (!abortController.signal.aborted) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown error';
        console.error('Error fetching session analytics data:', err);
        if (retryCount < 3) {
          setRetryCount(prev => prev + 1);
        } else {
          setError(errorMessage);
        }
      }
    } finally {
      if (!abortController.signal.aborted) {
        setLoading(false);
        setRefreshing(false);
        abortControllerRef.current = null;
      }
    }
  }, [dateFilter, customStartDate, customEndDate, callProcedure, retryCount]);

  useEffect(() => {
    fetchData();
    return () => { abortControllerRef.current?.abort(); };
  }, [fetchData]);

  useEffect(() => {
    if (retryCount > 0 && retryCount <= 3) {
      const timer = setTimeout(() => { fetchData(); }, 2000 * retryCount);
      return () => clearTimeout(timer);
    }
  }, [retryCount, fetchData]);

  const handleDateFilterChange = useCallback((value: string): void => {
    setDateFilter(value);
    setShowCustomDateRange(value === 'custom');
    if (value !== 'custom') {
      setCustomStartDate('');
      setCustomEndDate('');
    }
  }, []);

  const handleRefresh = useCallback(() => fetchData(true), [fetchData]);

  const handleCustomDateApply = useCallback((): void => {
    if (validateDateRange(customStartDate, customEndDate)) {
      fetchData();
    } else {
      setError('Invalid date range. Please ensure start date is before end date.');
    }
  }, [customStartDate, customEndDate, fetchData]);

  const stats = useMemo(() => {
    if (!rows || rows.length === 0) return {
      total: 0, active: 0, completed: 0, free: 0,
      paid: 0, autoGenerated: 0, withTranscription: 0,
    };
    const latestRow = rows[rows.length - 1];
    return {
      total: Number(latestRow.total_sessions) || 0,
      active: Number(latestRow.active_sessions) || 0,
      completed: Number(latestRow.completed_sessions) || 0,
      free: Number(latestRow.free_sessions) || 0,
      paid: Number(latestRow.paid_sessions) || 0,
      autoGenerated: Number(latestRow.auto_generated_sessions) || 0,
      withTranscription: Number(latestRow.sessions_with_transcription) || 0,
    };
  }, [rows]);

  const computedDateRange = useMemo(() => {
    const now = new Date();
    if (dateFilter === 'today') {
      const todayStr = now.toISOString().split('T')[0];
      return { first: todayStr, last: todayStr };
    }
    if (dateFilter === 'custom') {
      if (customStartDate && customEndDate) {
        return { first: customStartDate, last: customEndDate };
      }
      return { first: '', last: '' };
    }
    const days = parseInt(dateFilter, 10);
    if (!isNaN(days) && days > 0) {
      const start = new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
      return {
        first: start.toISOString().split('T')[0],
        last: now.toISOString().split('T')[0],
      };
    }
    return { first: '', last: '' };
  }, [dateFilter, customStartDate, customEndDate]);

  const { first, last } = computedDateRange;

  const activeFilterLabel = useMemo(() => {
    if (dateFilter === 'custom' && customStartDate && customEndDate) {
      return `${formatDateString(customStartDate)} – ${formatDateString(customEndDate)}`;
    }
    const found = DATE_FILTERS.find(f => f.value === dateFilter);
    return found?.label || 'All Time';
  }, [dateFilter, customStartDate, customEndDate, formatDateString]);

  return (
    <Page title="Session Analytics">
      <div className={`p-4 sm:p-7 sm:px-8 min-h-[calc(100vh-64px)] font-sans relative transition-colors duration-300 ${isDark ? ' text-slate-100' : 'bg-slate-50 text-slate-900'} rounded-2xl`}>

        <AnalyticsHeader
          title="Session Analytics"
          subtitle="Sessions overview & breakdown"
          isDark={isDark}
          dateFirst={first}
          dateLast={last}
          dateFilter={dateFilter}
          onDateFilterChange={handleDateFilterChange}
          dateFilters={DATE_FILTERS}
          loading={loading}
          refreshing={refreshing}
          onRefresh={handleRefresh}
          showCustomDateRange={showCustomDateRange}
          customStartDate={customStartDate}
          setCustomStartDate={setCustomStartDate}
          customEndDate={customEndDate}
          setCustomEndDate={setCustomEndDate}
          onCustomDateApply={handleCustomDateApply}
          formatDateString={formatDateString}
        />

        <AnalyticsError error={error} isDark={isDark} />

        <div className="grid grid-cols-1 min-[480px]:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4 mb-6">
          {STAT_CARDS.map(({ key, label, icon: Icon, accent }) => (
            <AnalyticsStatCard
              key={key}
              label={label}
              value={stats[key as keyof typeof stats]}
              icon={Icon}
              isDark={isDark}
              accent={accent}
              period={activeFilterLabel}
              progress={60}
            />
          ))}
        </div>

        <AnalyticsChartContainer
          title="Sessions Over Time"
          isDark={isDark}
          loading={loading}
          hasData={rows.length > 0}
          error={error}
          height="h-[220px] sm:h-[400px]"
          dateFirst={first}
          dateLast={last}
          formatDateString={formatDateString}
        >
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={rows} margin={{ top: 10, right: 8, left: -15, bottom: 0 }}>
              <defs>
                {SERIES.map((s) => (
                  <linearGradient key={s.key} id={`grad-${s.key}`} x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={s.color} stopOpacity={0.4} />
                    <stop offset="95%" stopColor={s.color} stopOpacity={0} />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke={isDark ? '#1e293b' : '#e2e8f0'} />
              <XAxis dataKey="date" tick={{ fill: isDark ? '#475569' : '#9ca3af', fontSize: 11 }} interval="preserveStartEnd" />
              <YAxis className="hidden sm:block" tick={{ fill: isDark ? '#475569' : '#9ca3af', fontSize: 11 }} />
              <Tooltip content={<AnalyticsTooltip isDark={isDark} />} />
              <Legend wrapperStyle={{ color: isDark ? '#94a3b8' : '#6b7280', fontSize: 13, paddingTop: 12 }} />
              {SERIES.map((s) => (
                <Area
                  key={s.key}
                  type="monotone"
                  dataKey={s.key}
                  name={s.label}
                  stroke={s.color}
                  strokeWidth={2}
                  fill={`url(#grad-${s.key})`}
                  dot={false}
                  activeDot={{ r: 5 }}
                />
              ))}
            </AreaChart>
          </ResponsiveContainer>
        </AnalyticsChartContainer>

      </div>
    </Page>
  );
}
