export interface DateFilterOptions {
  label: string;
  value: string;
  days: number;
}

export interface SeriesConfig {
  key: string;
  label: string;
  color: string;
}

export interface StatCardProps {
  label: string;
  value: number;
  badge?: string;
  isDark: boolean;
  icon?: any;
}

export interface CustomTooltipProps {
  active?: boolean;
  payload?: Array<{
    name: string;
    value: number | string;
    color: string;
    dataKey?: string;
    payload?: any;
  }>;
  label?: string;
  isDark: boolean;
}

export interface SubscriptionRef {
  listener: unknown;
  knexPg: unknown;
}

export interface SessionDataRow {
  date: string;
  total_sessions: number;
  active_sessions: number;
  completed_sessions: number;
  free_sessions: number;
  paid_sessions: number;
  auto_generated_sessions: number;
  manual_sessions: number;
  sessions_with_transcription: number;
  simple_language_sessions: number;
  multi_language_sessions: number;
}

export interface SessionAnalyticsStats {
  total: number;
  active: number;
  completed: number;
  free: number;
  paid: number;
  autoGenerated: number;
  withTranscription: number;
}

export interface CacheEntry<T> {
  data: T;
  timestamp: number;
}
